version: '3.8'

services:
  werewolf-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: werewolf-game
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - TZ=UTC
    labels:
      - "com.werewolf.description=One Night Ultimate Werewolf Game"
    networks:
      - werewolf-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  werewolf-network:
    driver: bridge

# Optional: Add volumes for persistent data or logs
# volumes:
#   nginx-logs:
#     driver: local
